### ISSUE TITLE
Check if sbuild keys exist at first launch

### ISSUE THREAD

**Issue by LeoIannacone** [debomatic/debomatic#10]
On a fresh installation, debomatic fails with:
```
ERROR: /var/lib/sbuild/apt-keys/sbuild-key.sec not found
ERROR: Launch "sbuild-update --keygen" to create valid keys
```

To fix it, you must run the following by hand:
```
$ sbuild-update --keygen
```

Since debomatic comes as an automatic tool, should it check that that file exists before start, instead to exit with error?

**Comment by dktrkranz** [comment]
My initial thought was the sysadmin has to create it manually to integrate with existing sbuild workflows, but it could make sense to create as if it's not there, sbuild won't work anyway...
