### ISSUE TITLE
In Modules pre_chroot/post_chroot, args.action is None

### ISSUE THREAD

**Issue by LeoIannacone** [debomatic/debomatic#11]
We expect that action is always something like 'create' or 'update'.

But here https://github.com/debomatic/debomatic/blob/f738ca28fc12058d0b8577f2179ffcc345946fc4/Debomatic/build.py#L274 action is set to None and its value never changes.

You use it also to check if chroot must be created, so please consider to use another variable.

**Comment by dktrkranz** [comment]
The former "update" is no longer in place, so the only action needed is "create" nowadays. What we could do is to set it to "present" or similar, but basically it becomes a no-op, unless it's needed in -webui somehow...

**Comment by LeoIannacone** [comment]
So, basically,

in JSONLogger I can skip the calls with actions = None ... which have no-sense.


PS: What happened to "chroot_update", no need in sbuild ??

**Comment by dktrkranz** [comment]
Nothing to change here anymore, closing.
