### ISSUE TITLE
Correctly handle experimental distribution

### ISSUE THREAD

**Issue by dktrkranz** [debomatic/debomatic#16]
The correct behavior of experimental should be:
 * Always install packages from unstable unless stated
 * Allow to install packages from experimental when required

Make sure Deb-o-Matic matches this.

**Comment by Fantu** [comment]
@dktrkranz this issue reappaired, I suppose is regression caused by replace aptitude with aspcud https://github.com/debomatic/debomatic/commit/ffa99d520862bbedbabdeb43a115bf814e70aa53
