### ISSUE TITLE
docs: submenus are not collapsed in left sidebar

### ISSUE THREAD

**Issue by anarcat** [debomatic/debomatic#30]
the table of contents on the documentation site in http://deb-o-matic.readthedocs.io/ seems to lack the normal collapsible items in other table of contents. it seems that all headings are shown in a single flat list instead of the usual collapsible hierarchy. here a screenshot of the behavior here:

![image](https://cloud.githubusercontent.com/assets/796623/19410155/d875cb22-92b2-11e6-954a-f71e1b22d007.png)

this is on Chromium in Debian stable: Version 53.0.2785.143 Built on 8.6, running on Debian 8.6 (64-bit). i see the same in Firefox 45.

it could be that is because everything is in a single rst file. rst documents can be split among multiple files, which makes them easier to read from source but also makes it easier to build a proper table of contents. the current rendering on RTD is broken I think because of that. i would suggest making one section per file to clear things up a bit, with index.rst being just an introduction to the package and showing a table of contents. this way, index.rst could also be reused as a README file or better, just _include_ a README file that would sit on top.

**Comment by dktrkranz** [comment]
Hi @anarcat, can you suggest where the rendering on RDT is broken?

**Comment by anarcat** [comment]
i guess rendering is not "broken", that was a bit of a misfire... i guess the issue here is that I find the table of contents on the left hard to navigate because it is "flat". for example on this browser here, the "Configuration" section is followed by "Configuration file", "debomatic section", and so on, all flattened. Here is a screenshot:

![image](https://cloud.githubusercontent.com/assets/796623/19410155/d875cb22-92b2-11e6-954a-f71e1b22d007.png)

when i click the "plus" button, the menu items, oddly enough, all regroup under the submenu and things go back to normal until i click the "minus" button again, going back to the above state.

i will clarify the original report - i was focusing on what i thought the solution was, instead of describing the problem more clearly, apologies.

**Comment by dktrkranz** [comment]
@anarcat do you have other examples on readthedocs I can take inspiration from?

**Comment by anarcat** [comment]
sure:

http://monkeysign.readthedocs.io/en/2.x/install.html
http://stressant.readthedocs.io/en/latest/install.html

etc.

**Comment by dktrkranz** [comment]
Thanks, latest commits should have made the trick, see [latest documentation](http://deb-o-matic.readthedocs.io/en/latest/)
