### ISSUE TITLE
Package build cannot chmod files such that they are unreadable or unwriteable

### ISSUE THREAD

**Issue by spwhitton** [debomatic/debomatic#31]
My package's test suite, run using an `override_dh_auto_test` stanza in `debian/rules`, fails on `debomatic-i386.debian.net` because it cannot render a file unreadable nor unwriteable.

The package is an Emacs Lisp library providing functions including predicates to test if a file is unreadable or unwriteable.  The test suite runs `chmod 000 foo.txt`, and then invokes the library's functions to see whether foo.txt is unreadable.  Similarly, the test runs `chmod 400 foo.txt` and then invokes the library's function to see whether foo.txt is unwriteable.  In both cases the function returns false instead of true.

The test suite entries for predicates that return whether a file is executable or not pass successfully.  And the package builds successfully in a local sbuild and a local pbuilder on my own machine.  So is there something in debomatic's configuration that might be causing this?  Thanks.

**Comment by dktrkranz** [comment]
Hi, sorry it took quite some time to answer. Do you still have your package available, so I can do some tests?

**Comment by spwhitton** [comment]
Dear Luca,

On Sat, Oct 15, 2016 at 01:22:58AM -0700, Luca Falavigna wrote:
> Hi, sorry it took quite some time to answer. Do you still have your package
> available, so I can do some tests?

Yes: the f-el source package available from the Debian archive.

-- 
Sean Whitton

**Comment by dktrkranz** [comment]
I launched a local sbuild build with this command:
`sbuild -A -s -d unstable --arch=i386 -c unstable-i386-debomatic f-el_0.19.0-1.dsc`

It failed too, so I suspect this is related to overlayfs, as my chroots are using that method.

This is my chroot configuration:
`[unstable-i386-debomatic]
type=directory
union-type=overlay
description=Debian unstable/i386 autobuilder
directory=/srv/debomatic-i386/unstable/unstable
groups=root,sbuild
root-groups=root,sbuild
profile=debomatic
personality=linux32`

**Comment by spwhitton** [comment]
Hello Luca,

Thanks again for looking at this.

I use sbuild with overlayfs locally, and the test suite passes.  So it
can't be that simple.

-- 
Sean Whitton

**Comment by dktrkranz** [comment]
I've reproduced this issue on my local PC, so it could be sbuild is faulty here, as it fails manually invoking sbuild too.

Could you please indicate which command you used in your local sbuild call, so I can try to debug it further?

**Comment by spwhitton** [comment]
I just call `sbuild` from the unpacked source package, and as I said, it works fine.

Here is my schroot config:

    [unstable-i386-sbuild]
    type=directory
    union-type=overlay
    description=Debian unstable/i386 autobuilder
    directory=/srv/chroot/unstable-i386
    groups=root,sbuild
    root-groups=root,sbuild
    profile=sbuild
    aliases=sid,rc-buggy,experimental,UNRELEASED,UNRELEASED-i386-sbuild
    command-prefix=/var/cache/ccache-sbuild/sbuild-setup,eatmydata

And my sbuild config:

    $pgp_options = ['-us', '-uc'];
    
    # `dht make-all` doesn't like this
    #$build_source = 1;
    $build_arch_all = 1;
    $distribution = 'unstable';
    
    $run_lintian = 1;
    $lintian_opts = [
        '--allow-root',
        '--color=never',            # make the .build file more readable
        '--fail-on-warnings',
        '--display-info'
        ];
    
    $run_piuparts = 1;
    $piuparts_opts = [
        '--schroot',
        '%r-%a-piuparts',
        '--fail-if-inadequate',
        # '--fail-on-broken-symlinks', # too many false positives
        '--log-level=info',
        ];
    
    $run_autopkgtest = 1;
    $autopkgtest_root_args = "";
    $autopkgtest_opts = ["--", "schroot", "%r-%a-sbuild"];
    
    1;

Sorry I can't be of more help.

**Comment by dktrkranz** [comment]
I tried reporting this issue in sbuild itself, as I think the problem lays there: https://bugs.debian.org/842232

**Comment by rhertzog** [comment]
@dktrkranz What makes you think this? Does it build with dpkg-buildpackage on your system?

**Comment by dktrkranz** [comment]
@rhertzog yes, I was able to. Have you been able to reproduce this bug with "plain" dpkg-buildpackage?

**Comment by josch** [comment]
Funny, I cannot reproduce your finding with sbuild 0.72.0-2. I'm running:

    sbuild -d unstable f-el

And my `~/.sbuildrc` says:

    $build_arch_all = 1;
    $run_lintian = 1;
    $lintian_opts = ['--pedantic', '--display-info', '--display-experimental'];
    $autopkgtest_root_args = '';
    $run_autopkgtest = 1;
    $autopkgtest_opts = [ '--', 'schroot', '%r-%a-sbuild' ];
    $run_piuparts = 1;
    $piuparts_opts = ['--schroot', '%r-%a-piuparts', '--fail-if-inadequate', '--log-level=info' ];

I'm using a directory-type schroot chroot with overlayfs.

**Comment by rhertzog** [comment]
I can't reproduce it either. To me it looks like something kernel related or something wrapper-related... do you have any special security module enabled? On my side, I have apparmor enabled but that is all running 4.7.0-1-amd64. I don't have any special wrapper (no eatmydata, nothing).

**Comment by dktrkranz** [comment]
Me neither. What surprises me is with dpkg-buildpackage works, but with the sbuild call mentioned above I can't build the package. I haven't tried with a non-overlayfs chroot yet, but I'll try that too.

**Comment by dktrkranz** [comment]
Today I tested in a schroot without overlayfs support, and failed too. I'm running out of ideas...
Anyway, this is definitely not a debomatic bug as I can reproduce with standard sbuild, so I'd move the discussion on the sbuild bug.

**Comment by spwhitton** [comment]
Fair enough.  Wish I could reproduce it.  If you have time, perhaps you
could file the sbuild bug, since you are able to reproduce it.

-- 
Sean Whitton

**Comment by dktrkranz** [comment]
Done already, see https://bugs.debian.org/842232

**Comment by spwhitton** [comment]
Thanks again!

-- 
Sean Whitton
