### ISSUE TITLE
A package compiles with pbuilder and sbuild and fails on debomatic

### ISSUE THREAD

**Issue by SnarkBoojum** [debomatic/debomatic#32]
Hi,

the acorn package which can be git-cloned from [here](https://anonscm.debian.org/git/pkg-javascript/acorn.git), builds perfectly with pbuilder, and with sbuild locally, but fails on debomatic (see [here](https://anonscm.debian.org/git/pkg-javascript/acorn.git)).

In case it helps, the error shouldn't happen because of the "ln -s dist/index.js acorn.js" after the series of mkdir.

Thanks,

Snark on #debian-js

**Comment by dktrkranz** [comment]
Could it similar to #31?

**Comment by LocutusOfBorg** [comment]
this seems a little different, it works on sbuild local, pbuilder local, sbuild on ppa, but the only sbuild instance where it fails seems to be on DoM (I think I even tried a porterbox)

**Comment by dktrkranz** [comment]
Same the other bug, where I could only reproduce on the DoM servers. I expect this is related to some specific configuration of the server (kernel / filesystem / whatnot).

**Comment by dktrkranz** [comment]
I tried to reproduce the issue after upgrading my build farm to stretch, and the problem seems to have vanished, therefore I think this was related to the machine / kernel configuration.

[acorn_4.0.4-2.buildlog.txt](https://github.com/debomatic/debomatic/files/1087129/acorn_4.0.4-2.buildlog.txt)
