### ISSUE TITLE
please build as non-root

### ISSUE THREAD

**Issue by smcv** [debomatic/debomatic#36]
Debian packages are normally built as an ordinary user, but it appears debomatic is building as root. This results in ostree failing a test that is normally skipped: <http://debomatic-amd64.debian.net/distribution#experimental/ostree/2017.11-1/buildlog>. I've seen other packages that FTBFS as root (but work fine as other uids) in the past.

I think debomatic should build as non-root, unless the scenario being tested is "what happens if we build as root?"

**Comment by smcv** [comment]
debomatic also seems to be using a non-standard umask (possibly 002) which, again, could make packages FTBFS. This seems like another thing that should only be done if the point of the archive rebuild is to exercise it.

**Comment by mapreri** [comment]
umask 002 shouldn't make packages FTBFS, and IMHO packages failing with it are just buggy.
As it so happens, also reproducible builds builds packages with varying umasks, 022 vs 002.

**Comment by smcv** [comment]
> umask 002 shouldn't make packages FTBFS, and IMHO packages failing with it are just buggy.

Sure, but if you're using debomatic to test something else (for instance what happens if you rebuild everything against gjs/experimental, which is why I was notified about this particular build failure), then unrelated variations from what would normally happen on official buildds can easily lead to false positives. (Or false negatives, for that matter.)

It turns out the current ostree will FTBFS if it's built as root *and* the umask isn't 022 (fix already sent upstream), but builds fine if either of those factors doesn't apply.

See also Policy bug [#835451: Building as root should be discouraged](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835451)

**Comment by dktrkranz** [comment]
https://bugs.debian.org/802849 needs to be fixed first.

**Comment by ntyni** [comment]
Just a note that we've been patching debomatic to run as non-root (without no-network since that requires root) for quite some time on perl.debian.net. A runtime configuration option for such a setup would be much appreciated.

**Comment by dktrkranz** [comment]
> Just a note that we've been patching debomatic to run as non-root

@ntyni, mind sharing the patch? Could be interesting to eventually merge it in case I'll manage to work arond the root limitation for no-network.

**Comment by ntyni** [comment]
On Mon, Jul 22, 2019 at 06:30:31AM -0700, Luca Falavigna wrote:
> > Just a note that we've been patching debomatic to run as non-root
> 
> @ntyni, mind sharing the patch? Could be interesting to eventually merge it in case I'll manage to work arond the root limitation for no-network.

IIRC these three trivial things were needed:

 https://salsa.debian.org/perl-team/perl.debian.net/debomatic/blob/master/debian/patches/no_no_network.patch

 https://salsa.debian.org/perl-team/perl.debian.net/debomatic/blob/master/debian/patches/run_as_non_root.patch

 https://salsa.debian.org/perl-team/perl.debian.net/debomatic/blob/master/debian/patches/fix_pid_path.patch

Thanks for looking at this,
-- 
Niko
