### ISSUE TITLE
unable to use debomatic repository

### ISSUE THREAD

**Issue by Fantu** [debomatic/debomatic#51]
Hi, after long time without using it, today I used http://debomatic-amd64.debian.net for build a package in unstable, build is ok but I'm unable to install it.
I tried to add it in apt sources.list:
`deb [trusted=yes] http://debomatic-amd64.debian.net/debomatic/unstable/ unstable main`
but apt update seems ignore it and I not understand why:
```
Scaricamento di:6 http://debomatic-amd64.debian.net/debomatic/unstable unstable InRelease [2.325 B]
Ignorato:6 http://debomatic-amd64.debian.net/debomatic/unstable unstable InRelease
```
@dktrkranz Is something I missed or did wrong? Or is there something not working?
thanks for any reply, sorry for my bad english and sorry if I posted this in wrong place

**Comment by dktrkranz** [comment]
Works fine for me. I'm able to see packages there with apt policy, for instance:
`(unstable-amd64-debomatic)root@misc-debomatic1:~# apt policy nemo
nemo:
  Installed: (none)
  Candidate: 4.6.5-1
  Version table:
     4.6.5-2~ 1
          1 http://debomatic-amd64.debian.net/debomatic/unstable unstable/main amd64 Packages
     4.6.5-1 500
        500 http://ftp.debian.org/debian unstable/main amd64 Packages
(unstable-amd64-debomatic)root@misc-debomatic1:~#`

**Comment by Fantu** [comment]
thanks for the reply, I solved adding "-t unstable" I didn't remember was needed
