### ISSUE TITLE
can debomatic support riscv64?

### ISSUE THREAD

**Issue by yuzibo** [debomatic/debomatic#55]
Hi,
I must admit that I'm not very familiar with these debomatic affairs. Because in past monthes 
I focus on helping Debian riscv64 porting and others bugfix.
From the hardware status section on [Hardware status](https://wiki.debian.org/Hardware/Wanted#Available_hardware), I know there is no
support riscv64 on debomatic from my view. So can we add support riscv64 here?

If so, I am not sure we need how many riscv64 hardware resoureces like Unmatched? Is it support remote access with ssh way?
Now I can find some riscv64 [hardware resoureces](https://github.com/plctlab/riscv-lab-access) to support debomatic, but the number is unknown.

The plct lab now has supported Debian riscv64 porting for[ buildd](https://buildd.debian.org/status/architecture.php?a=riscv64&suite=sid) team, [debci](https://ci.debian.net/status/) team, sals-ci team is deploing.

Please let me know if there is any issue.

BR,
Bo

**Comment by dktrkranz** [comment]
Hi,

debomatic can run in bare metal provided the dependencies are satisfied (python3/sbuild/etc…), which should normally be the case.

Otherwise, it can integrate with qemu to simulate real hardware although debomatic is running on another architecture: all my non-x86 architectures are running on amd64 emulated by qemu.

**Comment by yuzibo** [comment]
> debomatic can run in bare metal provided the dependencies are satisfied (python3/sbuild/etc…), which should normally be the case.
Ok. These dependencies will be satisfied on plct lab's Unmatched boards.
From my view, The role of the debomatic project is similar to portbox, right? If so, I think it's more convenient for Debian maintainer to debug issues on riscv64 hardware.
Just not sure, if remote access is ok for you? I can add your pubkey to have a look if you want.:)
> 
> Otherwise, it can integrate with qemu to simulate real hardware although debomatic is running on another architecture: all my non-x86 architectures are running on amd64 emulated by qemu.
yeah，qemu is common as simulate if we do not have real hardware. But sometime there is still a big difference in behavior between the both.

**Comment by dktrkranz** [comment]
> Ok. These dependencies will be satisfied on plct lab's Unmatched boards. From my view, The role of the debomatic project is similar to portbox, right? If so, I think it's more convenient for Debian maintainer to debug issues on riscv64 hardware. 

It’s more a buildd in the end, of course having real hardware to run on is preferable to avoid issues with qemu itself.

**Comment by dktrkranz** [comment]
RISCV64 support is available in the debomatic farm at http://debomatic-riscv64.debian.net

**Comment by yuzibo** [comment]
Great! Many Thanks.
