### ISSUE TITLE
put the arch in the buildlog file name

### ISSUE THREAD

**Issue by mapreri** [debomatic/debomatic#7]
Please use a buildlog file name that include the arch, similar to the one used by sbuild:

packagename_uversion-drevision_arch.log

I don't really care about the extension, but I'd like to collect all build logs from all arches in a single directory, currently unfeasible without renaming them.

**Comment by dktrkranz** [comment]
Handled in commit 631817b18f4003e13b751e1813d13578f562f3c6 as part of sbuild migration.
